name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter_localizations: # Add this line
    sdk: flutter 
  flutter:
    sdk: flutter
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_triple: ^1.2.7+2
  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  # image_path: "assets/icons/logo.png"
  # image_path_ios: "assets/icons/logo.png"
  # image_path_android: "assets/icons/logo.png"
  # adaptive_icon_background: "assets/images/splashscreen.png"
  # adaptive_icon_foreground: "assets/images/splashscreen.png"

flutter_native_splash:
#   background_image: "assets/images/splashscreen.png"
# flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/